[build]
  command = "remix build"
  publish = "public"
  
[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "remix watch"
  port = 3000

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
    
[[headers]]
  for = "/_static/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
