[build]
  command = "npm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
